### PR TITLE
ci: add test coverage for format binary

### LINKED ISSUE #121: [Bug]: JSON format does not seem to be supported
### What happened?

There is no way to format json files using this tool. It looks like there is scaffolding for it in `format.sh` but then it is never called.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: bazel 6.3.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: rules_lint-0.10.0

Language(s) and/or frameworks involved: json

### How to reproduce

_No response_

### Any other information?

I will hopefully get to submitting a PR myself but in case I do not I wanted to put this issues out there in case another contributor beat me to it.

### PR DESCRIPTION
**Pull request by alexeagle**
I suggested this in https://github.com/aspect-build/rules_lint/commit/18ca19086309ef587ab22dde09db3135cb79f7d0

> Note, there ought to be more testing that would have caught this. I spent some time writing a bats test here 

Should be able to catch most regressions this way.

Fixes #121 

---

### Type of change

- Chore (any other change that doesn't affect source or test files, such as configuration)

### Test plan

- New test cases added

### CODE REVIEW

File: format/private/format.sh [hunk 1]
```diff
@@ -140,6 +140,13 @@ if [ -n "$files" ] && [ -n "$bin" ]; then
   echo "$files" | tr \\n \\0 | xargs -0 $bin $prettiermode
 fi
 
+files=$(ls-files JSON $@)
```
Comment (alexeagle) [inline format/private/format.sh:143]: @IamXander I think this is the fix for #121

Comment (IamXander) [reply format/private/format.sh:143]: This looks right to me. Originally it was nice to have this as a separate tool so I could introduce this to my company's repo language by language. I would just turn it on for JSON, then I would enable it on more things. However, that is not a big deal so I am totally fine with this.

Comment (alexeagle) [reply format/private/format.sh:143]: I agree that still might make sense in a follow-up PR, especially if there's an alternative tool for JSON (I removed YAML from the prettier scope a while ago because someone said it's not the best choice there)

In fact, we should maybe have a 1:1 mapping between the language attributes on `multi_formatter_binary` and the list of languages in the GitHub Linguist sync (https://github.com/aspect-build/rules_lint/blob/main/format/private/filter.jq#L3-L22) - and that should happen before this repo can go to 1.0.

Would love to have more contributions :)

Comment (IamXander) [reply format/private/format.sh:143]: After this merges should I reopen https://github.com/aspect-build/rules_lint/pull/123/files to give json and other a distinct tool entry? Is that your suggestion?

**Review by gregmagolan — APPROVED** [review]
🌯

File: format/private/format.sh (hunk 1 above)
Comment (alexeagle) [reply format/private/format.sh:143]: I'm not sure. The downside is that a user will have repeat `lang1: prettier, lang2: prettier, etc..` attributes which doesn't seem very ergonomic either. Let's start with an issue for it so there's a place to discuss.
